CREATE DATABASE GESTION_PEDIDOS_BBDD;
USE GESTION_PEDIDOS_BBDD;
CREATE TABLE USUARIOS
( ID_USUARIO INT auto_increment PRIMARY KEY,
NOMBRE VARCHAR(50) NOT NULL,
EMAIL VARCHAR(50) NOT NULL UNIQUE,
PASSWORD VARCHAR(45) NOT NULL,
ENABLED INT,
ROL VARCHAR(45) NOT NULL,
FECHA_REGISTRO DATE,
CHECK (ENABLED IN (1,0)),
CHECK (ROL IN ('ADMIN','CLIENTE'))
);

INSERT INTO USUARIOS VALUES
(1,'Ramon', 'ramon@gmail.com', 'ramoncin', 1, 'ADMIN', '1997-01-15'),
(2,'Tomas', 'tomas@gmail.com', 'tomasin', 1, 'CLIENTE', '2001-01-15'),
(3,'Eva', 'eva@gmail.com', 'evita', 1, 'CLIENTE', '2002-01-15');

CREATE TABLE CATEGORIAS
( ID_CATEGORIA INT auto_increment primary KEY,
NOMBRE VARCHAR(45) NOT NULL,
DESCRIPCION VARCHAR(250)
);
INSERT INTO CATEGORIAS VALUES
(1,'Ropa', 'Prendas de Hombre mujer y niño'),
(2,'Calzado', 'De vestir, zapatos y zapatillas'),
(3,'Complementos', 'Cinturones, Fular, Bolsos');



CREATE TABLE PRODUCTOS
(ID_PRODUCTO INT auto_increment PRIMARY KEY,
NOMBRE VARCHAR(250) NOT NULL,
PRECIO DEC(11,2),
STOCK INT,
ID_CATEGORIA INT NOT NULL,
FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA)
);
INSERT INTO PRODUCTOS VALUES
(1,'Camisa fit Talla XS de Mujer entallada', 45,50,1),
(2,'Camisa regular  Talla M de Mujer', 75,50,1),
(3,'Falda regular Talla M de Mujer entallada', 45,50,1),
(4,'Camisa fit Talla L de Hombre ajustada', 145,50,1);



CREATE TABLE PEDIDOS
( ID_PEDIDO INT auto_increment PRIMARY KEY,
FECHA DATE,
ID_USUARIO INT NOT NULL,
FOREIGN KEY(ID_USUARIO) references USUARIOS(ID_USUARIO)
);
INSERT INTO PEDIDOS VALUES
(1,'2024-02-12', 2),
(2,'2024-05-02', 2),
(3,'2024-06-07', 2),
(4,'2024-07-15', 3),
(5,'2024-10-12', 3);



CREATE TABLE LINEAS_PEDIDO
( NUMERO_ORDEN INT auto_increment PRIMARY KEY,
ID_PEDIDO INT NOT NULL,
ID_PRODUCTO INT NOT NULL,
CANTIDAD INT,
PRECIO_UNITARIO DEC(11,2),
FOREIGN KEY(ID_PEDIDO) references PEDIDOS(ID_PEDIDO),
FOREIGN KEY(ID_PRODUCTO) references PRODUCTOS(ID_PRODUCTO),
UNIQUE(ID_PEDIDO, ID_PRODUCTO)
);

INSERT INTO LINEAS_PEDIDO VALUES
(1,1,1,2,45),
(2,1,2,2,70),
(3,1,3,2,30),
(4,2,1,2,45),
(5,3,2,2,70),
(6,4,1,2,45),
(7,5,2,2,70),
(8,5,4,4,145);

COMMIT;

